<?php
//点击系统和客服系统用同一套key，客服系统在gamekey.yaml文件上
return [
    'jzxjz'=>[
//        'key'=>'xw1svfhll6gufdpjfoshx2yyz3f8253o'
        'key'=>'xw1svfhll6gufdpjfoshx2yyz3f8253o',
        'need_change_uid'=>0
    ],
    'mori'=>[
        'key'=>'htu7oijlrljpirr7ahcvqln18fotqo0r',
        'need_change_uid'=>0
    ],
    'cyd'=>[
        'key'=>'Ximzu1RmAxo3ifqp4tpRhrU8uPCypj0o',
        'need_change_uid'=>0
    ],
    'qingyun'=>[
        'key'=>'JpSuuCM0p2QyWvtn8ZdilIJ3mAK37Kit',
        'need_change_uid'=>0
    ],
    '555'=>[
        'key'=>'87214810fa97f84f5fb94cfd1084ac6c',
        'need_change_uid'=>0
    ],
    'shenqi'=>[
        'key'=>'QnagbQ9XO5sygh4QrY4TrhMIgE0yyWqj',
        'need_change_uid'=>0
    ],
    'bxcq'=>[
        'key'=>'9Au9NGWVm1VyOqSIxeMNzc3t4KaldYRk',
        'need_change_uid'=>1
    ],
    'mxw'=>[
        'key'=>'gLswvWS3ppYXEu5tbBo4dn6bVePuIdAs',
        'need_change_uid'=>0
    ],
	'sxj'=>[
        'key'=>'07oYgI5g1wuHQQvSEBmOPsC0bkbHu4Gu',
        'need_change_uid'=>0
    ],
    'cs'=>[
        'key'=>'j5pVn8YorxMLorOEDst8z3R0gIChSKzI',
        'need_change_uid'=>1
    ],
    'y9cq'=>[
        'key'=>'v7iumyXmOjYc1yXML0xDLGFkIU4INTvy',
        'need_change_uid'=>0
    ],
    '555fl'=>[
        'key'=>'XXi947Yyyw6cAGQxbeW3JhxpbyzCNMSO',
        'need_change_uid'=>0
    ],
    'shenqiios'=>[
        'key'=>'Ky2ed8xzrz2vJ6I42TGjhpaN5C6aRFD0',
        'need_change_uid'=>0
    ],
    'lmzh'=>[
        'key'=>'ZOoBRqcBMTMbOO6l7qFgP567zWNVYoKo',
        'need_change_uid'=>0
    ],
    'hjgz'=>[
        'key'=>'vdo7srxaGpTEjrpZtl1guT0LAmRUaW4b',
        'need_change_uid'=>0
    ],
    '555fl-ll'=>[
        'key'=>'l0UodrBu0EWYXDwpPWOAJxyAsVulpJGY',
        'need_change_uid'=>0
    ],
    'rxhj'=>[
        'key'=>'1z2OWORtIogSkOAWCmiKR145Vllxb1O5',
        'need_change_uid'=>1
    ],
    'y8cl'=>[
        'key'=>'4jtPU96Ug68voB6trr9QUanzcduMN8SB',
        'need_change_uid'=>0
    ],
    'csios'=>[
        'key'=>'k40b5ku27TZG6qe7m38xels0prgtLIie',
        'need_change_uid'=>1
    ],
    'tjqy'=>[
        'key'=>'u75KCfQJ1sQzYTIxVBwewRM1MMwGDVa0',
        'need_change_uid'=>0
    ],
    'y9cqjh'=>[
        'key'=>'v7iumyXmOjYc1yXML0xDLGFkIU4INTvy',
        'need_change_uid'=>1
    ],
    'slsm'=> [
        'key'=>'bRtoKiZBM0Df6J9CXnVTbjBSNNQ14fa1',
        'need_change_uid'=>0
    ],
    'y9cqios'=>[
        'key'=>'v7iumyXmOjYc1yXML0xDLGFkIU4INTvy',
        'need_change_uid'=>0
    ],
    'wyxx'=>[
        'key'=>'zkPPk13diLLim08zP2cQQTs12Ql3Vvvb',
        'need_change_uid'=>1
    ],
    'xycq'=>[
        'key'=>'FX6pArxtZVhe1elBjXLr92bjCAM4Jvec',
        'need_change_uid'=>0
    ],
    'qj'=>[
        'key'=>'2xAWaEingwY07zNEOrBdQF0dxlQ6xiQY',
        'need_change_uid'=>1
    ],
    'yscqios'=>[
        'key'=>'YM0uDyIQ6OGRmsbmb92JP0xj6RVlDQDv',
        'need_change_uid'=>1
    ],
    'fycq'=>[
        'key'=>'W2IbsGhoBLHBZYv5I8DnZTtmf3x5DEkN',
        'need_change_uid'=>1
    ],
    '555xyx'=>[
        'key'=>'OM5UqpzfDcUZ5YJ2FFDELvOl6EaZZxXF',
        'need_change_uid'=>0
    ],
    'yscqyy'=>[
        'key'=>'ysjsnjlXSgRlHgHlwLyzQ0KqSjSFEBze',
        'need_change_uid'=>1
    ],
    'jzxyx'=>[
        'key'=>'i1sEmZVJdWg4wZ7oFFNTH1PIPwOyLtLf',
        'need_change_uid'=>0
    ],
    'jzezf'=>[
        'key'=>'EbMRjB62wmC7Tlt1vNefcXieQBHOa8Rd',
        'need_change_uid'=>1
    ],
    'nbcq'=>[
        'key'=>'ExEQePlw2cvCeBeWpXzeN55dr7tMTJqV',
        'need_change_uid'=>1
    ],
    'sbqj'=>[
        'key'=>'LDiyHyucosUsD3k5tsd3t8vwicFgbWGS',
        'need_change_uid'=>0
    ],
    'dxcq'=>[
        'key'=>'aynFd4NFnBRotvZDUjmZ3ykkw5Vqiu1a',
        'need_change_uid'=>1
    ],
    'xycqyy'=>[
        'key'=>'57MSIQOuuNRVyE6vMXQ1GvOtH6PO5UHE',
        'need_change_uid'=>0
    ],
    'ahgn'=>[
        'key'=>'WLM1B2IJiUi4rxJ4PHJNMqihvVdEvHWG',
        'need_change_uid'=>0
    ],
    'jmxy'=>[
        'key'=>'wLovREBpwLBa3MP7MSfKk2PPnBJaLZP3',
        'need_change_uid'=>1
    ],
    'ts'=>[
        'key'=>'Uf3gRj8y3yI9hp77VTxJpKgjWfCRIRge',
        'need_change_uid'=>0
    ],
    'nbcqios'=>[
        'key'=>'kneOHVMTo65DLd2Zb2MPtoTHopsD9HVZ',
        'need_change_uid'=>0
    ],
    'nbcq2youyu'=>[
        'key'=>'gPD0Ghfskd4O4KBEdpeGo8ic0vWlZgQo',
        'need_change_uid'=>1
    ],
    'nbcq2zw'=>[
        'key'=>'Py3DEFFW1EhaZNSXLln5UhxAtDSc2bdZ',
        'need_change_uid'=>1
    ],
    'rxxcx'=>[
        'key'=>'LWmJ8nVYLopoKKTRDc1UJQs68U7uxIE8',
        'need_change_uid'=>0
    ],
    'xgz'=>[
        'key'=>'FVBQNwgbLUtmDJKIp1N5t7zm35cNNBWm',
        'need_change_uid'=>1
    ],
    'gz3'=>[
        'key'=>'vrXCzGqqiFwK6dSlRSSc8yl6EkMWqS3U',
        'need_change_uid'=>0
    ],
    'bx555'=>[
        'key'=>'Jwex4CaryHf4MBjJdMBHS3EbSdhmN2hX',
        'need_change_uid'=>0
    ],
    'dxcq2'=>[
        'key'=>'rR8fG3RK8c25UT4pnetUVEwqvBFBNsRq',
        'need_change_uid'=>1
    ],
    'nbcqxyx'=>[
        'key'=>'0EQ9MxZGXI4TI2J07VeAneEYSRMrYjXP',
        'need_change_uid'=>0
    ],
    'nbcqxyxyy'=>[
        'key'=>'2FhwHm4ykFiFDxvWvvbRJ7uY5tKimUyN',
        'need_change_uid'=>0
    ],
    'sgcq'=>[
        'key'=>'zyShYdSFHq9iELv2DHEus2UgzYs4sPJa',
        'need_change_uid'=>1
    ],
    'nbcq2iosyouyu'=>[
        'key'=>'74NV47bR34CpdxCjwzgDqdOGq3ha6Dpo',
        'need_change_uid'=>0
    ],







];
